### ISSUE TITLE
List CVE entries for distributions

### ISSUE THREAD

**Issue by FROGGS** [cpants/www-cpants#100]
Would it be possible to list CVEs for the given package and version?
This way one could query this information and evaluate that when running CI tests.

I can imagine that this would not be an easy task, for at least these reasons:
- There might not be an easy way to find the correct vendor/product in the CVE database.
- The CVE scan needs to happen regularly after the release of the package has happened.

**Comment by charsbar** [comment]
It might be nice, and I suppose it's at least possible because nvd.nist.gov has several vulnerability feeds. However, I'm not sure if it's really worth implementing because I'm afraid it would be fairly rare for CPAN distributions to have their own CVEs. (https://www.cvedetails.com/google-search-results.php?q=cpan shows only 155 results as of this writing.)

**Comment by reneeb** [comment]
This might be easier now as https://metacpan.org/pod/CPAN::Audit exists.

**Comment by charsbar** [comment]
Thanks. Done with the help of CPAN::Audit. cf https://cpants.cpanauthors.org/release/BINGOS/Archive-Tar-2.22
