### ISSUE TITLE
Allow README.md as README file?

### ISSUE THREAD

**Issue by asb-capfan** [cpants/www-cpants#106]
https://cpants.cpanauthors.org/release/SRCHULO/DataTables-0.07 shows the Kwalitee issue has_readme. 
However, the module has a readme in MarkDown format, with the file ending .md

Would it make sense to also allow README.md files? Or maybe even other file extensions, like .txt or .rtf?

**Comment by charsbar** [comment]
CPANTS supports README.md and some other formats: https://github.com/cpants/Module-CPANTS-Analyse/blob/master/lib/Module/CPANTS/Kwalitee/Files.pm#L122

However, it looks like you have forgotten to update your MANIFEST after you renamed README as README.md, and thus when you made the distribution, README.md was not included in the tarball because it was not manifested. See https://metacpan.org/source/SRCHULO/DataTables-0.07 and https://metacpan.org/source/SRCHULO/DataTables-0.07/MANIFEST#L4 . 

So, update your MANIFEST and make a new release and then the problem should be gone.
