### ISSUE TITLE
erroneous "use_strict" error

### ISSUE THREAD

**Issue by rwfranks** [cpants/www-cpants#121]
Report for Net-DNS-SEC 1.12 complains that SEC.pm does not use strict.

It does, and always has.

**Comment by charsbar** [comment]
Sorry for the inconvenience and thanks for spotting this. This turns out to be a bug in Perl::PrereqScanner::NotQuiteLite that wrongly keeps an "eval" flag after a code like ```eval($VERSION);```, which in turn makes it consider ```use strict;``` after that line is in an eval block and thus the ```strict``` is a suggested module, not required. I'm running a test using minicpan to see if a fix for this has no side effect.

**Comment by rwfranks** [comment]
Looks like it is fixed now, thanks
