### ISSUE TITLE
HDB::Object uses Class::HPLOO but not listed in Users tab

### ISSUE THREAD

**Issue by hakonhagland** [cpants/www-cpants#123]
See 

https://cpants.cpanauthors.org/release/GMPASSOS/Class-HPLOO-0.23/used_by

and 

https://metacpan.org/release/HDB/source/lib/HDB/Object.pm#L35

**Comment by charsbar** [comment]
It is because your HDB distribution's META.yml says it only requires DBI.
https://metacpan.org/source/GMPASSOS/HDB-1.05/META.yml#L8

Generally speaking, CPAN toolchain including CPANTS trusts META files more than what's declared in each .pm file, because the latter may be a conditional requirement (consider Win32 module in ::Win32 namespace in some distributions, which is not supposed to be used by other OS users, and thus, can't be declared as a solid requirement in META files). In this case Class::HPLOO is considered such a conditional module, and thus, is ignored.
