### ISSUE TITLE
http://cpants.cpanauthors.org/dist/Test-Run-TAP-Model yields "Page Not Found"

### ISSUE THREAD

**Issue by shlomif** [cpants/www-cpants#48]
The link http://cpants.cpanauthors.org/dist/Test-Run-TAP-Model (that can be found here - http://cpants.cpanauthors.org/author/SHLOMIF ) yields "Page Not Found" / "Raptor Not Found". Please look into fixing it.

**Comment by dolmen** [comment]
This appears to be fixed.

**Comment by shlomif** [comment]
It is fixed now, so I'm going to close this issue. Note however, that this issue was not dealt with for over 2 years since reporting it which is indicative of grave mismanagement.

**Comment by dolmen** [comment]
"grave mismanagement" seems a bit abusive for a service that @charsbar is providing for free on his free time with his own money for hosting.
And nothing says here that the issue was not already fixed two years ago. I just try to help triaging the issue queue and noticed it does not appear NOW.

**Comment by shlomif** [comment]
@dolmen : I apologise for my wording.

**Comment by charsbar** [comment]
@shlomif , you don't need to apologise. Less-than-ideal management was just a fact. I suppose one of the earlier commits (maybe this https://github.com/cpants/www-cpants/commit/184477985bf6905f59caf8aba9505db30889fa01 , maybe not) should have fixed your issue accidentally, but I haven't noticed that because I was so busy at that time (actually, have almost always been since around that time) and couldn't have time to review everything. I still haven't had time to write enough tests for this issue, but as this was quite a rare case, forgive me if I'd rather implement other stuff with higher priorities first.

Anyway, thanks for your patience, and thanks for your report. You know patches are always welcome :)

@dolmen, honestly, what made me much sadder was your "political-correct" comment on my behalf. I'm grateful for your kindness but I'd also like to let you know that I haven't been offended by that "grave mismanagement" at all, partly because it was just a fact and partly because I am a Japanese who usually don't use English (well, I, as a translator, frequently read/write English, but that's that) and live in a different culture. What made me sad was your not showing (or finding) a clue of your "nothing says here the issue was not already fixed two years ago" statement, I've said to you elsewhere that you shouldn't say "fixed" until we write a test to ensure. The same thing applies here: I'd like you not to say about "fixed" (or "not-yet-fixed") status until you find a clue to support your statement, as you're not someone unrelated but a member of this orga.

**Comment by dolmen** [comment]
@charsbar 

> I still haven't had time to write enough tests for this issue, but as this was quite a rare case, forgive me if I'd rather implement other stuff with higher priorities first.

I'm sorry: I was not aware about how much automated testing for this kind of issue was important to you. As for #5 I only did manual testing to check that 404 is not returned. I only stated that fact with the "it appears" precaution. I did not close the issue. I have absolutely no knowledge of the code base and so should have kept my mouth closed. Understood.
