### ISSUE TITLE
`no dot dirs` false positive

### ISSUE THREAD

**Issue by dolmen** [cpants/www-cpants#59]
In my distribution [POE-Component-Schedule](http://cpants.cpanauthors.org/dist/POE-Component-Schedule), the Kwalitee metric `no dot dirs` is raised.
In this particular case, this is about the [.settings directory](https://metacpan.org/source/DOLMEN/POE-Component-Schedule-0.95) that contains the [Eclipse EPIC](http://www.epic-ide.org/) project file that could be reused by another Perl developer when patching. This is completely deliberate.

How can I disable this check?

**Comment by kentfredric** [comment]
> Hey, this is not FALSE positive! :)

I disagree. Dot dirs have functions outside that of use by SCMS. Some people may have intentional dotdirs instead of accidental ones, for whatever reason.

> They just bloat the size of the tarball, and CPAN needlessly.

This seems subjective based on "need", as you're basically asserting we don't "need" a dotdir.

I'd propose something smarter like a blacklist of known SCM dotdirs that are less subjectively useless and more subjectively painful than a blanket "dot dirs are bad" policy.

**Comment by kentfredric** [comment]
And I doubt you'd argue the same thing about dotfiles, of which, many are necessary and useful in a dist *for contributors* **even** when shipped. Like `.vimrc`  and `.perltidyrc` for instance.

The distinction between a dot "file" and a dot "dir" is purely conceptual. 

Given 3 tools that store identical content in a "dot" of some kind, one could store all its data
in a single flatfile ( a dotfile ), and your policy would say "Thats ok", while another would cluster its contents into multiple files in a dotdir, and another would create a collection of prefixed dotfiles like

    .tool_filea
    .tool_fileb
    .tool_filec

And yet this heuristic says "The first and the last are both ok, but not the second".

I consider that inconsistent and arbitrary.

If your intent is to isolate crufty scm files, have a policy that explicitly indicates those.

**Comment by charsbar** [comment]
>I'd propose something smarter like a blacklist of known SCM dotdirs that are less subjectively useless and more subjectively painful than a blanket "dot dirs are bad" policy.

Blacklist tends to fail to catch something new. Catch all and exclude white would be better as dot dirs are usually hidden and their inclusion tends to be overlooked. See the following list (dot dir(s) and their occurence). Is there anything that you think should be considered _widely_ accepted and marked white, even for Windows users for whom dot dirs are not particularly hidden? 

.MT|1
.aline|1
.author|6
.build|23
.bzr|7
.carton|3
.dotest|5
.ec|4
.generated_pod|1
.gimp-1.2|1
.git|200
.git,.komodotools|5
.hg|12
.komodotools|4
.libs|3
.local-v5.14|1
.options|18
.pc|1
.pgp|9
.push|1
.settings|39
.svn|74
.test_mimic_data|1
.test_mimic_recorder_data|1
.toader|2
.vim|1
.xvpics|2

**Comment by charsbar** [comment]
> And I doubt you'd argue the same thing about dotfiles, of which, many are necessary and useful in a dist for contributors even when shipped. Like .vimrc and .perltidyrc for instance.

"no_dot_files" metric is pended because the list gets much longer (~3300 files, though ~2400 of them are dot underscore files, which are covered by "no_dot_underscore_files" metric), and it's harder to say which is useful and which is not. Maybe we can add something more to catch notable temporary files such as *.swp (~280 files), but that's another issue.

**Comment by kentfredric** [comment]
`.vim` **may** be of use to have in a shipped dist for purposes of a workflow where people intend to submit patches vs cpan releases. (ie: if it has some sort of settings that apply codebase wide indentation settings). I'm not sure, I've never seen that dir in the wild on a dist and having trouble ascertaining what its used for without example. ( Nothing in vims documentation seems to indicate anything about it ).

But I'm explaining this as such so you can see my reasoning.

- Assume some dists do still not have a git repo or similar
- Or assume some dists authors intend for their published dists to be suitable for writing patches against directly.
- Assume some dists also want to have a "git repo vanished" contingency ( where having a directly patch-and-releasable `$RELEASE[-1]` is desirable )

Given those two points, files that help keep code consistent with the projects style would be useful to preserve.

So given that rationale, the following *may* be wanted to be kept ( but require further analysis ):

- `.komodotools` :  Because they probably have code layout settings for users who edit it with komodo
- `.settings` : ^ For the same reasons but with some other editing tool
- `.options` : ^ because it looks like the above

( And those are also dirs I'd expect to see on some random non-perl project as well )

**Comment by kentfredric** [comment]
You could also consider adjusting the metrics so dot-dirs/dot-files were only errors if they were over a certain aggregate size, because "It wastes space" is IMO a more useful concern than "It looks nasty", and that would allow a certain threshold of dot-content of arbitrary names before the policy was inflamed.
