### ISSUE TITLE
Unnecessary prereq flagging for SDL modules

### ISSUE THREAD

**Issue by frezik** [cpants/www-cpants#90]
My distro got flagged for missing prereqs among the SDL family of modules:

http://cpants.cpanauthors.org/dist/Game-Asset-SDLSound

The missing modules (SDL::Mixer, SDL::Mixer::Music, and SDL::RWOps) are all part of the SDL distribution package, which is correctly listed as a prereq already. My general feeling is that prereqs should note the overall CPAN distribution, not individual modules. I am open to arguments otherwise.

At a guess, the problem may be that SDL has a bit of a messy history on CPAN, with several people releasing several related versions over the years. New releases didn't always overwrite the old ones. I'm betting CPANTS is grabbing one of the older ones, sees that SDL::Mixer, etc. are not part of it, and then flagging the prereqs.

**Comment by charsbar** [comment]
Thanks for the report. As you guessed correctly, this problem is happening because SDL-2.544 (the previous release) declared in the "provides" section in the META files that the subordinate modules in the distribution have version "0"s, and SDL-2.546 (the latest) declares they don't have versions, and thus most of the subordinate modules like SDL::Mixer etc are still tied with 2.544 in the 02packages.details.txt (CPAN index), which means, from the CPAN index'es point of view, the latest SDL doesn't have proper SDL::Mixer etc (because of the version regression), though they are actually bundled in the distribution and declared in the META files.

In this case, as both SDL-2.544 and SDL-2.546 have SDL::Mixer etc, this version mismatch may not be a real problem, but generally speaking, that isn't always true, because, for example, SDL::Mixer (without version) is also bundled in SDL-sdlpl distribution (https://metacpan.org/release/SDL-sdlpl), which may override a part of an SDL distribution.

Raised an issue for the SDL team. https://github.com/PerlGameDev/SDL/issues/285

**Comment by FROGGS** [comment]
https://github.com/PerlGameDev/SDL/issues/285 is resolved now and should be available on cpan in the next hours.

**Comment by charsbar** [comment]
Thanks
