### ISSUE TITLE
Core kwalitee is 99.42%

### ISSUE THREAD

**Issue by benkasminbullock** [cpants/www-cpants#92]
All the modules currently have 100% score:

http://cpants.cpanauthors.org/author/BKB

All of the modules have been at 100% for quite a while now, but still the Core Kwalitee is 99.42.

Is there something I've overlooked?

**Comment by charsbar** [comment]
This happened because you have several distributions entirely deleted from CPAN, and the CPANTS analyzer had mistakenly counted those latest BackPAN distributions while calculating average kwalitee. Fixed with https://github.com/cpants/www-cpants/commit/207b345f626db369a4a9d386365991e1e1f4f518 . Thanks.
