### ISSUE TITLE
Pod::Text::Overstrike module abstract missing

### ISSUE THREAD

**Issue by rra** [cpants/www-cpants#99]
At https://cpants.cpanauthors.org/release/RRA/podlators-4.10 the abstract for Pod::Text::Overstrike is blank. I'm not sure why this would be; I can't find anything different in the source module that would cause it to be treated differently.

**Comment by charsbar** [comment]
Because Pod::Text::Overstrike has a ```for``` section between its ```head1``` section and a paragraph that's supposed to be an abstract.
https://metacpan.org/source/RRA/podlators-4.10/lib/Pod/Text/Overstrike.pm#L144-150

ExtUtils::MakeMaker and Module::Build only look for an abstract text between ```head1``` and the following directive (in this case ```for```).
https://metacpan.org/source/BINGOS/ExtUtils-MakeMaker-7.35_03/lib/ExtUtils/MM_Unix.pm#L2842-2886

CPANTS uses the same logic as them, because it's a tool to indicate toolchain issues. It looks like search.cpan.org uses the same logic, too.
http://search.cpan.org/~rra/podlators-4.10/

MetaCPAN seems to use a different, probably more authentic Pod parser logic. However, it still has some issue because its abstract does have ```Pod::Text::Overstrike - ``` part, which others don't have, probably because of prepending whitespaces because of the ```for``` section.
https://metacpan.org/release/RRA/podlators-4.10

Moving the ```for``` section somewhere should fix all the above issues.
